# default: &default
#   adapter:                 postgresql
#   encoding:                   unicode
#   pool:    <%= ENV['DB_POOL_SIZE'] %>
#   port:         <%= ENV['DB_PORT'] %>
#   host:         <%= ENV['DB_HOST'] %>
#   username:     <%= ENV['DB_USER'] %>
#   password: <%= ENV['DB_PASSWORD'] %>

# development:
#   <<: *default
#   database:     <%= ENV['DB_NAME'] %>

# # test:
# #   <<: *default
# #   database: sgis_test

# # production:
# #   <<: *default
# #   database: sgis_production


default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL_SIZE'] || 5 %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_development

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>_production
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
